### ISSUE TITLE
Add multilingual support

### ISSUE THREAD

**Issue by h-enk** [h-enk/doks#114] opened 2021-02-05 15:40 UTC
## Summary

- [Multilingual Mode](https://gohugo.io/content-management/multilingual/)

### Basic example

- https://gifted-pasteur-36c387.netlify.app/ (English, default)
- https://gifted-pasteur-36c387.netlify.app/ru/ (Extra language)

### Motivation

- https://github.com/h-enk/doks/discussions/55
- https://github.com/h-enk/doks/discussions/101
- https://gitlab.com/epogrebnyak/doks-howto

**Comment by epogrebnyak** [comment] 2021-02-05 15:51
Should this involve a language switch for the theme? Could be a killer feature.

**Comment by h-enk** [comment] 2021-02-05 15:53
> Should this involve a language switch for the theme? Could be a killer feature.

Absolutely.

**Comment by epogrebnyak** [comment] 2021-02-05 15:54
Example of a switch, but exact good visual would be challenging to make: https://codeit.suntprogramator.dev/

**Comment by lostmaniac** [comment] 2021-03-30 10:08
I also need this feature

**Comment by dhassault** [comment] 2021-05-22 03:33
This would be great :rocket::rocket::rocket::rocket:

**Comment by epogrebnyak** [comment] 2021-06-27 19:56
We are using a homemade switch, but we need to maintain the duplicate of the documents so that language docs do not break. Ideally, the switch should be stable and have some stable behaviour if we do not have a corresponsing document in another language.

**Comment by h-enk** [comment] 2021-08-12 18:18
Just to inform: it's in the making, and available in 1-2 weeks time.

It will look something like this:

![Snag_262f6ad](https://user-images.githubusercontent.com/3902872/129248025-40b58ffb-2e34-4297-a56b-467d1e39ab40.png)

**Comment by h-enk** [comment] 2021-09-15 12:45
> We are using a homemade switch, but we need to maintain the duplicate of the documents so that language docs do not break. Ideally, the switch should be stable and have some stable behaviour if we do not have a corresponsing document in another language.

Implemented behavior in Doks:
- If a page is not available in the selected language, go to the homepage of that language

**Closed** 2021-09-15 12:45 UTC
Labels: enhancement

**Comment by h-enk** [comment] 2021-09-15 12:46
Implemented w/ https://github.com/h-enk/doks/pull/454, documentation /usage to be added
