### ISSUE TITLE
Italics not supported by default?

### ISSUE THREAD

**Issue by nk9** [h-enk/doks#604] opened 2022-01-09 16:07 UTC
## Description

I have text which uses italics. This is done with the underscore in Markdown, and the generated HTML uses the &lt;em&gt; tag. But the output doesn't show the italic text.

### Steps to reproduce

Just use underscores to generate some italic text anywhere in page content. E.g.

```
Is the whale _dead_?
```

### Actual result

<img width="1057" alt="Screenshot 2022-01-09 at 16 02 43" src="https://user-images.githubusercontent.com/3646730/148690423-7e5944f4-42c3-41e6-84db-a09d3a421719.png">

### Environment

```
{
  'doks-child-theme': '0.3.5',
  npm: '8.3.0',
  node: '17.2.0',
  v8: '9.6.180.14-node.12',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '102',
  nghttp2: '1.46.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}
```

**Comment by h-enk** [comment] 2022-01-13 10:35
Can't reproduce this. For me, with the doks child theme, both `npm run start` and `npm run build` show the `<em>` tag like expected,

You could try adding the `<em>` tag to the safelist in `./config/postcss.config.js`.

Would you mind sharing your repo?

**Comment by nk9** [comment] 2022-01-14 14:20
Oh, very strange. This is happening on Firefox, but I see Safari and Chrome both working as expected. Adding the `em` tag to `postcss.config.js` doesn't fix the problem.

I'm on the most recent version of Firefox, 96.0, on macOS 11.6.2 (20G314).

Any other ideas what could be wrong?

**Comment by h-enk** [comment] 2022-01-14 16:11
Strange, indeed. It works for me (with a fresh doks child theme) on Firefox 96.0.1 (64bit), on Windows 10 Pro 21H2 19044.1466

So, it looks like something with the combination Firefox - macOS.

> I've added you to the theme, although you may not need it if you can see the issue in Firefox too.

Do you have the repo link?

**Comment by h-enk** [comment] 2022-01-14 16:16
Note, that the markdown gets converted correctly (see you screenshot). So, it's got to do something with the way Firefox (in combination w/ macOS) interprets the `<em>` tag.

**Comment by h-enk** [comment] 2022-01-14 16:24
I'm closing this issue, for this is out of scope for Doks.

**Comment by h-enk** [comment] 2022-01-22 15:59
Thanks! Your PR is welcome!

**Comment by h-enk** [comment] 2022-01-24 13:28
Hmm, I still can't reproduce your issue.

I've verified `https://getdoks.org/docs/recipes/alerts/` (no changes to `assets/scss/common/_fonts.scss`) on:

- Big Sur, Chrome latest + Safari latest + Firefox latest
- Montery, Chrome latest

But, all's looking good to me:

![Snag_20320bde](https://user-images.githubusercontent.com/3902872/150790683-0a0464e9-4fad-432e-850c-508d3f3c6d91.png)


![Snag_202a6cc1](https://user-images.githubusercontent.com/3902872/150789463-37727e80-027d-4eb6-bff6-0489c5a3231d.png)


![Snag_202ddbb9](https://user-images.githubusercontent.com/3902872/150790015-bb522100-1ec0-48af-befd-c90370356b14.png)

**Closed** 2022-01-31 13:28 UTC
